# Этот файл является обязательным для платформы extensions.blender.org
# This file is required for the extensions.blender.org platform

schema_version = "1.0.0"

# Уникальный идентификатор вашего аддона. Хорошая практика - использовать имя репозитория.
id = "ship-dragndrop-texture"

# Информация, которая будет отображаться на сайте
name = "Smart Drag & Drop Texture Set"
tagline = "Drag, drop, and get a full PBR material in seconds."
type = "ADDON" # Тип расширения: ADDON, THEME и т.д.

# Теги для поиска и категоризации
tags = ["Material", "PBR", "Texture", "Workflow", "Drag and Drop", "Game Development"]

# Информация о лицензии. Должна совпадать с лицензией на GitHub.
license = "GPL-3.0-or-later"

# Ссылки, которые появятся на странице вашего расширения
website = "https://github.com/shipworkshop/SHIP-DragNDrop-Texture"
documentation = "https://github.com/shipworkshop/SHIP-DragNDrop-Texture#readme"
tracker = "https://github.com/shipworkshop/SHIP-DragNDrop-Texture/issues"
