# =============================================================
#  Manifest for the Blender Extensions Platform
#  Final corrected version.
# =============================================================

schema_version = "1.0.0"
id = "ship_dragndrop_texture"
version = "1.1.0"
maintainer = "Yurii Konoplov (shipworkshop)"

# ОШИБКА 1: Исправлена минимальная версия Blender.
blender_version_min = "4.2.0"

name = "SHIP Drag and Drop Texture"
tagline = "Drag & drop, and get a full PBR material in seconds"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]

# ОШИБКА 2: Использованы только официальные теги из списка платформы.
tags = ["Material", "Node", "User Interface"]

website = "https://github.com/shipworkshop/SHIP-DragNDrop-Texture"
documentation = "https://github.com/shipworkshop/SHIP-DragNDrop-Texture#readme"
tracker = "https://github.com/shipworkshop/SHIP-DragNDrop-Texture/issues"
